# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Genevariation 3D"
email: "andreas@rcsb.org"
description: "A workshop to discuss interconnection of precision medicine, genetic variation data, protein sequence, and 3D structural information."
baseurl: ""
url: "http://genevariation3d.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-85181317-1"
googleAnalyticsSiteUrl: "genevariation3d.org"
siteVerification: "0p6-cgaWBJl3VReLF3lySDRuZ8G4huQfAX1SM4JqrBU"

# Organizer Info
organizerName: "genevariation3d.org"
organizerAlternateName: "Gene Variation 3D"
organizerDescription: "A Big Data Spoke Planning Grant and is part of the West Big Data Innovation Hub."
organizerEmail: "andreas@rcsb.org"
organizerLogo: "/img/about-section/snp3d.png"
organizerLink: "http://genevariation3d.org"

# Head
metaKeywords: "event, gene variation, precision medicine, workshop, proteomics, genomics, 3D structure, big data, west big data hub"
twitterAccount: "@ericwdeutsch"
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Program"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/usecases/", text: "Use Cases"}
 - {permalink: "/resources/", text: "Resources"}
 - {permalink: "/team/", text: "Team"}

bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout> Genevariation3d workshop 2017"
eventDate: "February 9th, 10th, 2017"
typeoutTextValues: '"", "Institute for Systems Biology", "Seattle", "Washington", "USA"'
typeoutFallback: "ISB"
heroButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Genevariation3d workshop"
aboutBlock:
 - {title: "Workshop", image: "conference.jpg", text: "A two-day workshop at the Institute for Systems Biology in Seattle, Washington, for collaborators and other researchers working toward the interconnection of precision medicine, genomic, proteomic, and protein structure data." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "2", specialCharacter: "+", info: "days", detail: "of Big Data technologies"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Institue of Systems Biology"
eventLocationLink: "https://www.systemsbiology.org"
eventStreetAddress: "401 Terry Ave N"
eventAddressLocality: "Seattle"
eventAddressLocalityRegion: "Washington"
eventPostalCode: "98109"
eventAddressCountry: "USA"
eventStartTime: "2016-02-09T08:00"
eventDoorTime: "09:00"
eventEndTime: "2016-02-10T20:00"
eventPlaceCoordinates: "47.62253, -122.33752 "
mapCenterCoordinates: "47.62253, -122.33752"
mapMobileCenterCoordinates: "47.62253, -122.33752"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Institute for Systems Biology"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "genevariation3d"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around early November 2016. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.rcsb.org", text: "www.rcsb.org"}
   - {link: "https://www.systemsbiology.org/", text: "Institute for Systems Biology"}
   - {link: "http://westbigdatahub.org/", text: "West Big Data Innovation Hub"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:andreas@rcsb,org", text: "andreas@rcsb.org"}
 -


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "genevariation3d"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "A two-day workshop at the Institute for Systems Biology in Seattle, Washington, for collaborators and other researchers working toward the interconnection of genomic, proteomic, and protein structure data. Our ultimate goal is to tie together genetic variation data with protein level information, by using the four established resources (and others, yet to be determined) as a driving force:"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "47.62253, -122.33752"
logisticsMapMobileCenterCoordinates: "47.62253, -122.33752"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Seattle"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://sea.aero">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Seattle. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Seattle.'}
 - {title: "Hotels", information: 'Seattle has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Use Cases"
enableHackathon: true

# Hackathon About Block
aboutUseCaseTitle: "Use Cases"
useCases:
 - {
    title: "Genomic architecture of inflammatory bowel disease in five families with multiple affected individuals",
    image: "IBD_protein_structure.png",
    details: "This Big Data Spokes Project aims to speed our understanding of genetic variants that are suspected of causing disease by instantly showing researchers a 3D model of the chemical effect of each variant. Because determining these effects is currently a laborious process requiring specialized skills, it is often not done in research on genetic variants. Here, we present a study of the genetic causes of inflammatory bowel disease, and show how our resource could have been employed to make the study faster and cheaper. ",
    link: "https://docs.google.com/document/d/1NmLOUoMCbGqYZjB98Ta0WzcGRQFbzqy0_Fufy125V0Q/pub",
    citation: "http://www.nature.com/articles/hgv201560"
   }


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

# Members block
membersTitle: "Members"
members:
 - {title: "RCSB Protein Data Bank", link: "http://rcsb.org", image: "rcsb_logo.png", info: "The Protein Data Bank (PDB) is a crystallographic database for the three-dimensional structural data of large biological molecules, such as proteins and nucleic acids."}
 - {title: "Kaviar", link: "http://db.systemsbiology.org/kaviar", image: "KaviarLogo.png", info: "database of human genomic variation"}
 - {title: "PeptideAtlas", link: "http://www.peptideatlas.org", image: "PeptideAtlas_Logo.png", info: "proteomics data compendium"}
 - {title: "Trans-Proteomic Pipeline", link: "http://tools.proteomecenter.org/wiki/index.php?title=Software:TPP", image: "software.png", info: "Trans-Proteomic Pipeline software"}
